name: Build Magisk Module

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Module version (e.g. 1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup module directory
      run: |
        # 创建临时构建目录
        mkdir build_temp
        # 移动所有模块文件到临时目录（排除指定文件）
        rsync -av \
          --exclude='README.md' \
          --exclude='.gitignore' \
          --exclude='.git/' \
          --exclude='.github/' \
          --exclude='build_temp/' \
          ./ build_temp/

    - name: Create Magisk module zip
      id: create_zip
      run: |
        # 进入临时目录（但不包含目录本身）
        cd build_temp
        
        # 设置压缩包名称
        ZIP_NAME="All-in-one-module_${{ inputs.version }}.zip"
        
        # 创建压缩包（只包含目录内容，不包含build_temp本身）
        zip -r -9 "../$ZIP_NAME" .
        
        # 返回上级目录并设置输出
        cd ..
        echo "ZIP_PATH=$(pwd)/$ZIP_NAME" >> $GITHUB_OUTPUT
        echo "Generated zip file: $ZIP_NAME"
        ls -lh "$ZIP_NAME"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: magisk-module
        path: ${{ steps.create_zip.outputs.ZIP_PATH }}
