name: Build Magisk Module

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Module version (e.g. 1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODULE_NAME: All-in-one-module  # 定义模块名称

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup module directory
      run: |
        # 创建临时构建目录
        mkdir build_temp
        # 移动所有模块文件到临时目录（排除指定文件）
        rsync -av --exclude='README.md' --exclude='.gitignore' --exclude='.git/' --exclude='.github/' ./ build_temp/

    - name: Create Magisk module zip
      run: |
        cd build_temp
        # 创建压缩包（确保只有一层结构）
        ZIP_NAME="${MODULE_NAME}_${{ inputs.version }}.zip"
        zip -r -9 "../$ZIP_NAME" *
        cd ..
        # 打印生成的文件路径用于调试
        echo "Generated zip file: $(pwd)/$ZIP_NAME"
        ls -lh "$ZIP_NAME"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: magisk-module
        path: ${{ env.MODULE_NAME }}_${{ inputs.version }}.zip
