name: Build Magisk Module

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Module version (e.g. 1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup module directory
      run: |
        # 创建临时构建目录
        mkdir build_temp
        # 移动所有模块文件到临时目录（排除.gitignore中指定的文件）
        rsync -av --exclude-from='.gitignore' --exclude='.git/' --exclude='.github/' ./ build_temp/

    - name: Create Magisk module zip
      run: |
        cd build_temp
        # 创建压缩包（确保只有一层结构）
        zip -r -9 ../${MODULE_NAME}_${{ inputs.version }}.zip *
        cd ..
      env:
        MODULE_NAME: All-in-one-module  # 可更改为你的模块名称

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: magisk-module
        path: ${{ env.MODULE_NAME }}_${{ inputs.version }}.zip
